# Generated by Django 2.1.7 on 2019-03-25 23:40

from django.db import migrations, models
import newsWebsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsWebsite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.ImageField(default='authorPictures/default_author.png', upload_to=newsWebsite.models.picture_upload_path),
        ),
    ]
