# Generated by Django 2.1.7 on 2019-03-27 17:48

from django.db import migrations, models
import newsWebsite.models


class Migration(migrations.Migration):

    dependencies = [
        ('newsWebsite', '0002_auto_20190325_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='heroImage',
            field=models.ImageField(blank=True, default='heroImages/default_article.png', max_length=500, upload_to=newsWebsite.models.hero_upload_path),
        ),
    ]
